### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brozow** [dzonekl/oss2nms#1]
If OpenNMS is licensed GPLv3 how can you port be licensed Apache 2.0?

**Comment by dzonekl** [comment]
What do you see is the issue with this? (GPLv3 having some tighter restrictions?, is not possible to license differently what I contribute, and then refer to GPLv3 for OpenNMS work?).

**Comment by dzonekl** [comment]
ok, I did a bit of research, perhaps you can check from your side as well. 
GPLv3 is strong copyleft. So using this code, requires the derivative work to not restrict the GPLv3. This is not possible with all OS licenses, but Apache licens 'seems' compatible with GPLv3, so it shoudn't be an issue. If you can not confirm this, I will change it to GPLv3, because I do not have any intention to make your work proprietary in whatever shape or form.

**Comment by dzonekl** [comment]
some more reading... 
http://radar.oreilly.com/2007/04/gplv3-apache-license-compatibi.html

It's a joke, that by intention the FSF, Apache, Eclipse etc... want to be compatible, but fail because of some minor clause. Others making software use these licenses (OpenNMS/NetXforge), but have to stick to theses disputes. So up to you, do you want to be strict, because GPLv3 is strict, or do you want to carry the spirit of Open Source. Your work is recognized (copy right headers in the code are untouched), and public (On this very github).

**Comment by brozow** [comment]
I don't have the freedom to give you a different license from the GPLv3 for OpenNMS.  The GPLv3 REQUIRES any derivative works to be licensed under the GPL.  In turn OpenNMS includes open source projects in one way or another and must abide by the requirements of those licenses.  As a result you must license your code as GPLv3 as well.

However, I wouldn't say that the GPLv3 is not carrying the spirit of Open Source.  In fact was the GPL and the FSF that created the Open Source movement.  The requirement of GPL just says that if you create a derivative work you must make it open source as well and those that make derivative works of yours must also be open source, and so on.  If, for example, you released you code as Apache.  The others could take your code and some lines and the license it completely closed source with none of those changes available to the users of that code.  With the GPL that is not possible.  All subsequent changes, improvements and additions must remain open.

**Comment by brozow** [comment]
By they way,  I am not commenting on this in anyway to detract from the great work you are doing.  It just so happens that some one else that is using OpenNMS just required me to do a complete audit of OpenNMS to protect them from license infringement.  I think your stuff is great and hopefully you will continue and I will gladly provide as much help as I can.  I just want to make sure that you were properly licensed as this protects both you and those who use your code.

Thanks for all of the hard working you are doing!!

**Comment by dzonekl** [comment]
Ok, it's clear. I will change the license and thanks for the kudos and offering your help. 

So you know, as the projects become full-class-citizen OSGI bundles, I am also changing the build structure. So the bundles and associated features will be build with Tycho. (Which is a maven plugin to build OSGI/Equinox artifacts). The dependencies will be packaged as OSGI bundles as well and published on a P2 repository, so these can be referred by a .target definition which is used by both Tycho and Eclipse IDE to have build-infra and IDE in sync.  

Perhaps you are not familiar with all these terms and technologies, but as this is what I know. There are some good things about this. As the bundles and features are all packaged separately these can be deployed and assembled in whatever shape or form, which was my primary motivation to start this. Tycho can also process so called .product definitions, which will generate OS independent versions of the build (win32, macosx, linux etc...). 

Finally the wiring of the modules is up for a change. What concerns me right now is the daemons, with start order, initialization etc.. There are several ways to go about. Either all daemon in one bundle or a bundle for each daemon. The latter has the advantage to be able to control the bundle start order for each individual daemon. The former could prove sufficient, but a routine is needed to make sure all daemon dependencies and initialization occurs.

On the DAO side, I haven't touched it yet, but I would like to see that it's isolated and inter-changeble. (As NetXStudio is now, I just  define the interface and use OSGI services / Dependency injection to bind it to an implementation).  I looked into Blueprint, but it's not common in Equinox land. Will investigate further.

**Comment by dzonekl** [comment]
300d81659246ac44ae9ba0bdc111514d0f44fe89
